name: CI - TrackHub Test & Build

on: [push, pull_request]

jobs:
  test-and-build:
    name: Test all services
    runs-on: ubuntu-latest

    services:
      postgres-auth:
        image: postgres:14
        env:
          POSTGRES_DB: user_manager
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      postgres-music:
        image: postgres:14
        env:
          POSTGRES_DB: music_manager
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 5433:5432

      postgres-notification:
        image: postgres:14
        env:
          POSTGRES_DB: email_manager
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 5434:5432

    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Test auth-service
        run: |
          cd API_userManagement/api
          mvn clean test

      - name: Test music-service
        run: |
          cd music-service
          mvn clean test

      - name: Test notification-service
        run: |
          cd notification-service
          mvn clean test

      - name: Docker containers test
        run: |
          docker compose -f docker-compose.yml up -d --build
          sleep 20